name: Backend CI - Tests

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]
  workflow_dispatch:

jobs:
  backend-tests:
    name: Run backend Maven tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Run Maven tests (generate surefire reports)
        working-directory: ./backend
        run: |
          echo "Running backend tests..."
          # Run Maven with verbose output and write to a log file for debugging. We keep -B (batch) but include -V and -e for more detail.
          mvn -B -V -e test 2>&1 | tee backend-maven.log

      - name: List surefire files
        working-directory: ./backend
        if: always()
        run: |
          echo "Listing surefire reports (backend/target/surefire-reports):"
          ls -la target/surefire-reports || echo "No surefire reports found"

      - name: Upload Maven log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-maven-log
          path: backend/backend-maven.log
          retention-days: 7

      - name: Upload surefire reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-reports
          path: backend/target/surefire-reports/**/*.xml
          retention-days: 7

      - name: Generate JaCoCo report
        if: always()
        working-directory: ./backend
        run: |
          echo "Generating JaCoCo HTML/XML reports..."
          mvn -B org.jacoco:jacoco-maven-plugin:0.8.10:report || true

      - name: Upload JaCoCo HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-jacoco-report
          path: backend/target/site/jacoco
          retention-days: 7

      - name: Create job summary (tests)
        if: always()
        working-directory: ./backend
        run: |
          python -u ../.github/scripts/parse_surefire.py $GITHUB_STEP_SUMMARY target/surefire-reports/*.xml || true
